### PR TITLE
Merge ign-transport8 ➡️  ign-transport11

### PR DESCRIPTION
**Pull request by chapulina**
# ➡️  Forward port

Port `ign-transport8 ` ➡️  `ign-transport11`

Branch comparision: https://github.com/ignitionrobotics/ign-transport/compare/ign-transport11...ign-transport8

**Note to maintainers**: Remember to **Merge** with commit (not squash-merge or rebase)

### CODE REVIEW

**Review by ahcorde — CHANGES_REQUESTED** [review]
this is not compiling 

```
  /github/workspace/src/cmd/ign_TEST.cc: In member function 'virtual void ignTest_ServiceHelpVsCompletionFlags_Test::TestBody()':
  /github/workspace/src/cmd/ign_TEST.cc:472:38: error: 'PROJECT_SOURCE_DIR' was not declared in this scope
     std::filesystem::path scriptPath = PROJECT_SOURCE_DIR;
```

**Comment by jennuine** [comment]
> this is not compiling
> 
> ```
>   /github/workspace/src/cmd/ign_TEST.cc: In member function 'virtual void ignTest_ServiceHelpVsCompletionFlags_Test::TestBody()':
>   /github/workspace/src/cmd/ign_TEST.cc:472:38: error: 'PROJECT_SOURCE_DIR' was not declared in this scope
>      std::filesystem::path scriptPath = PROJECT_SOURCE_DIR;
> ```

Should be fixed here: c0c54bb898685768a7e7d4cc952e7f3f4f386c79

@mabelzhang can you double check the updates I did were correct? I saw a couple `TODO`s in the `transport.bash_completion.sh` file

**Comment by mabelzhang** [comment]
Your updates look good to me. (and `UNIT_ign_TEST` is passing, that's how you know you did the `TODO`s right :D) Thanks!

**Comment by chapulina** [comment]
The new `UNIT_Discovery_TEST` failure isn't caused by this PR and is being investigated on #335

**Pull request merged**
