### PR TITLE
Remove deprecations in Harmonic

### PR DESCRIPTION
**Pull request by caguero**
# 🎉 Maintenance

Remove deprecations

## Checklist
- [x] Signed all commits for DCO
- [ ] Added tests
- [ ] Added example and/or tutorial
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if the library has them)
- [ ] `codecheck` passed (See [contributing](https://gazebosim.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://gazebosim.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Agazebosim+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

### CODE REVIEW

**Comment by mjcarroll** [comment]
@osrf-jenkins retest this please

**Comment by caguero** [comment]
@Crola1702 , do you know why the Ubuntu Focal CI gets stuck?

**Comment by Crola1702** [comment]
I think for harmonic we're not supporting Foca but Jammy, right? Maybe it's triggered as a Jammy job, but checks are expecting a Focal job :thinking:

**Comment by Crola1702** [comment]
Maybe @j-rivero has more context on this?

**Comment by caguero** [comment]
> I think for harmonic we're not supporting Focal but Jammy, right? Maybe it's triggered as a Jammy job, but checks are expecting a Focal job thinking

As far as I know it's only Jammy (and the future 24.04). Not sure why it's triggered...

**Comment by mjcarroll** [comment]
> As far as I know it's only Jammy (and the future 24.04). Not sure why it's triggered...

It's because this PR was opened before we disabled the focal job for the target branch.  It can safely be ignored.

**Comment by caguero** [comment]
> > As far as I know it's only Jammy (and the future 24.04). Not sure why it's triggered...
> 
> It's because this PR was opened before we disabled the focal job for the target branch. It can safely be ignored.

I see. I don't have superpowers to merge this PR without all the checks passing...

**Comment by mjcarroll** [comment]
Is the failing windows test okay?

**Comment by mjcarroll** [comment]
> I see. I don't have superpowers to merge this PR without all the checks passing...

I removed the branch protection check, can you merge it now?

**Pull request merged**
