### PR TITLE
Add tracing to the discovery test

### PR DESCRIPTION
**Pull request by mjcarroll**
Adds a whole bunch of output to figure out why the discovery unit test is failing all of a sudden.

### CODE REVIEW

**Comment by mjcarroll** [comment]
CC: @quarkytale to test on a focal box.

**Comment by quarkytale** [comment]
`uname -a`:
```
Linux dd-system76 5.17.5-76051705-generic #202204271406~1653440576~20.04~6277a18~dev-Ubuntu SMP PREEMPT Th x86_64 x86_64 x86_64 GNU/Linux
```
And the test `./build/gz-transport12/bin/UNIT_Discovery_TEST` outputs:
<details close>
<br/>
<pre>
```
Running main() from /home/dharini/gazebo/garden_ws/src/ign-transport/test/gtest_vendor/src/gtest_main.cc
[==========] Running 12 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 12 tests from DiscoveryTest
[ RUN      ] DiscoveryTest.TestBasicAPI
Discovery::Discovery(8c2d4624-4f83-4253-831d-20605d8da566, 224.0.0.7, 11319)
 No environment read: determineInterfaces
Discovery::RegisterNetIFace(10.0.0.195)
netIface == this->hostAddr 10.0.0.195 == 172.17.0.1
netIface == this->hostAddr[false]
succeed[true]
Discovery::RegisterNetIFace(172.17.0.1)
netIface == this->hostAddr 172.17.0.1 == 172.17.0.1
netIface == this->hostAddr[true]
succeed[true]
[       OK ] DiscoveryTest.TestBasicAPI (115 ms)
[ RUN      ] DiscoveryTest.WithoutCallingStart
Discovery::Discovery(8c2d4624-4f83-4253-831d-20605d8da566, 224.0.0.7, 11320)
 No environment read: determineInterfaces
Discovery::RegisterNetIFace(10.0.0.195)
netIface == this->hostAddr 10.0.0.195 == 172.17.0.1
netIface == this->hostAddr[false]
succeed[true]
Discovery::RegisterNetIFace(172.17.0.1)
netIface == this->hostAddr 172.17.0.1 == 172.17.0.1
netIface == this->hostAddr[true]
succeed[true]
[       OK ] DiscoveryTest.WithoutCallingStart (58 ms)
[ RUN      ] DiscoveryTest.TestAdvertiseNoResponse
Discovery::Discovery(8c2d4624-4f83-4253-831d-20605d8da566, 224.0.0.7, 11319)
 No environment read: determineInterfaces
Discovery::RegisterNetIFace(10.0.0.195)
netIface == this->hostAddr 10.0.0.195 == 172.17.0.1
netIface == this->hostAddr[false]
succeed[true]
Discovery::RegisterNetIFace(172.17.0.1)
netIface == this->hostAddr 172.17.0.1 == 172.17.0.1
netIface == this->hostAddr[true]
succeed[true]
Discovery::Discovery(5b6c2e7d-3c63-44fb-9b5c-c5b68a76fa38, 224.0.0.7, 11319)
 No environment read: determineInterfaces
Discovery::RegisterNetIFace(10.0.0.195)
netIface == this->hostAddr 10.0.0.195 == 172.17.0.1
netIface == this->hostAddr[false]
succeed[true]
Discovery::RegisterNetIFace(172.17.0.1)
netIface == this->hostAddr 172.17.0.1 == 172.17.0.1
netIface == this->hostAddr[true]
succeed[true]
[       OK ] DiscoveryTest.TestAdvertiseNoResponse (1226 ms)
[ RUN      ] DiscoveryTest.TestAdvertise
Discovery::Discovery(8c2d4624-4f83-4253-831d-20605d8da566, 224.0.0.7, 11319)
 No environment read: determineInterfaces
Discovery::RegisterNetIFace(10.0.0.195)
netIface == this->hostAddr 10.0.0.195 == 172.17.0.1
netIface == this->hostAddr[false]
succeed[true]
Discovery::RegisterNetIFace(172.17.0.1)
netIface == this->hostAddr 172.17.0.1 == 172.17.0.1
netIface == this->hostAddr[true]
succeed[true]
Discovery::Discovery(5b6c2e7d-3c63-44fb-9b5c-c5b68a76fa38, 224.0.0.7, 11319)
 No environment read: determineInterfaces
Discovery::RegisterNetIFace(10.0.0.195)
netIface == this->hostAddr 10.0.0.195 == 172.17.0.1
netIface == this->hostAddr[false]
succeed[true]
Discovery::RegisterNetIFace(172.17.0.1)
netIface == this->hostAddr 172.17.0.1 == 172.17.0.1
netIface == this->hostAddr[true]
succeed[true]
---------------
Enabled: false
Discovery state
	UUID: 5b6c2e7d-3c63-44fb-9b5c-c5b68a76fa38
Settings
	Activity: 100 ms.
	Heartbeat: 1000ms.
	Silence: 3000 ms.
Known information:
---
Activity
	<empty>
---------------

Received discovery update from 10.0.0.195: 11319
---------------
Enabled: true
Discovery state
	UUID: 5b6c2e7d-3c63-44fb-9b5c-c5b68a76fa38
Settings
	Activity: 100 ms.
	Heartbeat: 1000ms.
	Silence: 3000 ms.
Known information:
---
[928672934]
	Proc. UUID: 8c2d4624-4f83-4253-831d-20605d8da566
Publisher:
	Topic: [928672934]
	Address: tcp://127.0.0.1:12345
	Process UUID: 8c2d4624-4f83-4253-831d-20605d8da566
	Node UUID: 71af1017-4aef-462c-9db2-2373ca6e6624
	Control address: tcp://127.0.0.1:12346
	Message type: t
Advertise options:
	Scope: All
	Throttled? No
Activity
	8c2d4624-4f83-4253-831d-20605d8da566
		Since: 0 ms. ago. 
---------------
	* Sending HEARTBEAT msg []

Received discovery update from 172.17.0.1: 40762
---------------
Enabled: true
Discovery state
	UUID: 5b6c2e7d-3c63-44fb-9b5c-c5b68a76fa38
Settings
	Activity: 100 ms.
	Heartbeat: 1000ms.
	Silence: 3000 ms.
Known information:
---
[928672934]
	Proc. UUID: 8c2d4624-4f83-4253-831d-20605d8da566
Publisher:
	Topic: [928672934]
	Address: tcp://127.0.0.1:12345
	Process UUID: 8c2d4624-4f83-4253-831d-20605d8da566
	Node UUID: 71af1017-4aef-462c-9db2-2373ca6e6624
	Control address: tcp://127.0.0.1:12346
	Message type: t
Advertise options:
	Scope: All
	Throttled? No
Activity
	8c2d4624-4f83-4253-831d-20605d8da566
		Since: 0 ms. ago. 
---------------

Received discovery update from 10.0.0.195: 11319
---------------
Enabled: true
Discovery state
	UUID: 5b6c2e7d-3c63-44fb-9b5c-c5b68a76fa38
Settings
	Activity: 100 ms.
	Heartbeat: 1000ms.
	Silence: 3000 ms.
Known information:
---
[928672934]
	Proc. UUID: 8c2d4624-4f83-4253-831d-20605d8da566
Publisher:
	Topic: [928672934]
	Address: tcp://127.0.0.1:12345
	Process UUID: 8c2d4624-4f83-4253-831d-20605d8da566
	Node UUID: 71af1017-4aef-462c-9db2-2373ca6e6624
	Control address: tcp://127.0.0.1:12346
	Message type: t
Advertise options:
	Scope: All
	Throttled? No
Activity
	8c2d4624-4f83-4253-831d-20605d8da566
		Since: 0 ms. ago. 
---------------

Received discovery update from 172.17.0.1: 40762
---------------
Enabled: true
Discovery state
	UUID: 5b6c2e7d-3c63-44fb-9b5c-c5b68a76fa38
Settings
	Activity: 100 ms.
	Heartbeat: 1000ms.
	Silence: 3000 ms.
Known information:
---
[928672934]
	Proc. UUID: 8c2d4624-4f83-4253-831d-20605d8da566
Publisher:
	Topic: [928672934]
	Address: tcp://127.0.0.1:12345
	Process UUID: 8c2d4624-4f83-4253-831d-20605d8da566
	Node UUID: 71af1017-4aef-462c-9db2-2373ca6e6624
	Control address: tcp://127.0.0.1:12346
	Message type: t
Advertise options:
	Scope: All
	Throttled? No
Activity
	8c2d4624-4f83-4253-831d-20605d8da566
		Since: 0 ms. ago. 
---------------

Received discovery update from 10.0.0.195: 11319
---------------
Enabled: true
Discovery state
	UUID: 5b6c2e7d-3c63-44fb-9b5c-c5b68a76fa38
Settings
	Activity: 100 ms.
	Heartbeat: 1000ms.
	Silence: 3000 ms.
Known information:
---
[928672934]
	Proc. UUID: 8c2d4624-4f83-4253-831d-20605d8da566
Publisher:
	Topic: [928672934]
	Address: tcp://127.0.0.1:12345
	Process UUID: 8c2d4624-4f83-4253-831d-20605d8da566
	Node UUID: 71af1017-4aef-462c-9db2-2373ca6e6624
	Control address: tcp://127.0.0.1:12346
	Message type: t
Advertise options:
	Scope: All
	Throttled? No
Activity
	8c2d4624-4f83-4253-831d-20605d8da566
		Since: 0 ms. ago. 
---------------

Received discovery update from 172.17.0.1: 40762
---------------
Enabled: true
Discovery state
	UUID: 5b6c2e7d-3c63-44fb-9b5c-c5b68a76fa38
Settings
	Activity: 100 ms.
	Heartbeat: 1000ms.
	Silence: 3000 ms.
Known information:
---
[928672934]
	Proc. UUID: 8c2d4624-4f83-4253-831d-20605d8da566
Publisher:
	Topic: [928672934]
	Address: tcp://127.0.0.1:12345
	Process UUID: 8c2d4624-4f83-4253-831d-20605d8da566
	Node UUID: 71af1017-4aef-462c-9db2-2373ca6e6624
	Control address: tcp://127.0.0.1:12346
	Message type: t
Advertise options:
	Scope: All
	Throttled? No
Activity
	8c2d4624-4f83-4253-831d-20605d8da566
		Since: 0 ms. ago. 
---------------

Received discovery update from 10.0.0.195: 11319
---------------
Enabled: true
Discovery state
	UUID: 5b6c2e7d-3c63-44fb-9b5c-c5b68a76fa38
Settings
	Activity: 100 ms.
	Heartbeat: 1000ms.
	Silence: 3000 ms.
Known information:
---
[928672934]
	Proc. UUID: 8c2d4624-4f83-4253-831d-20605d8da566
Publisher:
	Topic: [928672934]
	Address: tcp://127.0.0.1:12345
	Process UUID: 8c2d4624-4f83-4253-831d-20605d8da566
	Node UUID: 71af1017-4aef-462c-9db2-2373ca6e6624
	Control address: tcp://127.0.0.1:12346
	Message type: t
Advertise options:
	Scope: All
	Throttled? No
Activity
	8c2d4624-4f83-4253-831d-20605d8da566
		Since: 0 ms. ago. 
---------------

Received discovery update from 172.17.0.1: 40717
---------------
Enabled: true
Discovery state
	UUID: 5b6c2e7d-3c63-44fb-9b5c-c5b68a76fa38
Settings
	Activity: 100 ms.
	Heartbeat: 1000ms.
	Silence: 3000 ms.
Known information:
---
[928672934]
	Proc. UUID: 8c2d4624-4f83-4253-831d-20605d8da566
Publisher:
	Topic: [928672934]
	Address: tcp://127.0.0.1:12345
	Process UUID: 8c2d4624-4f83-4253-831d-20605d8da566
	Node UUID: 71af1017-4aef-462c-9db2-2373ca6e6624
	Control address: tcp://127.0.0.1:12346
	Message type: t
Advertise options:
	Scope: All
	Throttled? No
Activity
	8c2d4624-4f83-4253-831d-20605d8da566
		Since: 0 ms. ago. 
---------------

Received discovery update from 10.0.0.195: 11319
---------------
Enabled: true
Discovery state
	UUID: 5b6c2e7d-3c63-44fb-9b5c-c5b68a76fa38
Settings
	Activity: 100 ms.
	Heartbeat: 1000ms.
	Silence: 3000 ms.
Known information:
---
[928672934]
	Proc. UUID: 8c2d4624-4f83-4253-831d-20605d8da566
Publisher:
	Topic: [928672934]
	Address: tcp://127.0.0.1:12345
	Process UUID: 8c2d4624-4f83-4253-831d-20605d8da566
	Node UUID: 71af1017-4aef-462c-9db2-2373ca6e6624
	Control address: tcp://127.0.0.1:12346
	Message type: t
Advertise options:
	Scope: All
	Throttled? No
Activity
	8c2d4624-4f83-4253-831d-20605d8da566
		Since: 0 ms. ago. 
---------------
	* Sending HEARTBEAT msg []

Received discovery update from 172.17.0.1: 40762
---------------
Enabled: true
Discovery state
	UUID: 5b6c2e7d-3c63-44fb-9b5c-c5b68a76fa38
Settings
	Activity: 100 ms.
	Heartbeat: 1000ms.
	Silence: 3000 ms.
Known information:
---
[928672934]
	Proc. UUID: 8c2d4624-4f83-4253-831d-20605d8da566
Publisher:
	Topic: [928672934]
	Address: tcp://127.0.0.1:12345
	Process UUID: 8c2d4624-4f83-4253-831d-20605d8da566
	Node UUID: 71af1017-4aef-462c-9db2-2373ca6e6624
	Control address: tcp://127.0.0.1:12346
	Message type: t
Advertise options:
	Scope: All
	Throttled? No
Activity
	8c2d4624-4f83-4253-831d-20605d8da566
		Since: 0 ms. ago. 
---------------

Received discovery update from 10.0.0.195: 11319
---------------
Enabled: true
Discovery state
	UUID: 5b6c2e7d-3c63-44fb-9b5c-c5b68a76fa38
Settings
	Activity: 100 ms.
	Heartbeat: 1000ms.
	Silence: 3000 ms.
Known information:
---
[928672934]
	Proc. UUID: 8c2d4624-4f83-4253-831d-20605d8da566
Publisher:
	Topic: [928672934]
	Address: tcp://127.0.0.1:12345
	Process UUID: 8c2d4624-4f83-4253-831d-20605d8da566
	Node UUID: 71af1017-4aef-462c-9db2-2373ca6e6624
	Control address: tcp://127.0.0.1:12346
	Message type: t
Advertise options:
	Scope: All
	Throttled? No
Activity
	8c2d4624-4f83-4253-831d-20605d8da566
		Since: 0 ms. ago. 
---------------

Received discovery update from 172.17.0.1: 40762
---------------
Enabled: true
Discovery state
	UUID: 5b6c2e7d-3c63-44fb-9b5c-c5b68a76fa38
Settings
	Activity: 100 ms.
	Heartbeat: 1000ms.
	Silence: 3000 ms.
Known information:
---
[928672934]
	Proc. UUID: 8c2d4624-4f83-4253-831d-20605d8da566
Publisher:
	Topic: [928672934]
	Address: tcp://127.0.0.1:12345
	Process UUID: 8c2d4624-4f83-4253-831d-20605d8da566
	Node UUID: 71af1017-4aef-462c-9db2-2373ca6e6624
	Control address: tcp://127.0.0.1:12346
	Message type: t
Advertise options:
	Scope: All
	Throttled? No
Activity
	8c2d4624-4f83-4253-831d-20605d8da566
		Since: 0 ms. ago. 
---------------

Received discovery update from 10.0.0.195: 11319
---------------
Enabled: true
Discovery state
	UUID: 5b6c2e7d-3c63-44fb-9b5c-c5b68a76fa38
Settings
	Activity: 100 ms.
	Heartbeat: 1000ms.
	Silence: 3000 ms.
Known information:
---
[928672934]
	Proc. UUID: 8c2d4624-4f83-4253-831d-20605d8da566
Publisher:
	Topic: [928672934]
	Address: tcp://127.0.0.1:12345
	Process UUID: 8c2d4624-4f83-4253-831d-20605d8da566
	Node UUID: 71af1017-4aef-462c-9db2-2373ca6e6624
	Control address: tcp://127.0.0.1:12346
	Message type: t
Advertise options:
	Scope: All
	Throttled? No
Activity
	8c2d4624-4f83-4253-831d-20605d8da566
		Since: 0 ms. ago. 
---------------

Received discovery update from 172.17.0.1: 40762
---------------
Enabled: true
Discovery state
	UUID: 5b6c2e7d-3c63-44fb-9b5c-c5b68a76fa38
Settings
	Activity: 100 ms.
	Heartbeat: 1000ms.
	Silence: 3000 ms.
Known information:
---
[928672934]
	Proc. UUID: 8c2d4624-4f83-4253-831d-20605d8da566
Publisher:
	Topic: [928672934]
	Address: tcp://127.0.0.1:12345
	Process UUID: 8c2d4624-4f83-4253-831d-20605d8da566
	Node UUID: 71af1017-4aef-462c-9db2-2373ca6e6624
	Control address: tcp://127.0.0.1:12346
	Message type: t
Advertise options:
	Scope: All
	Throttled? No
Activity
	8c2d4624-4f83-4253-831d-20605d8da566
		Since: 0 ms. ago. 
---------------

Received discovery update from 10.0.0.195: 11319
---------------
Enabled: true
Discovery state
	UUID: 5b6c2e7d-3c63-44fb-9b5c-c5b68a76fa38
Settings
	Activity: 100 ms.
	Heartbeat: 1000ms.
	Silence: 3000 ms.
Known information:
---
[928672934]
	Proc. UUID: 8c2d4624-4f83-4253-831d-20605d8da566
Publisher:
	Topic: [928672934]
	Address: tcp://127.0.0.1:12345
	Process UUID: 8c2d4624-4f83-4253-831d-20605d8da566
	Node UUID: 71af1017-4aef-462c-9db2-2373ca6e6624
	Control address: tcp://127.0.0.1:12346
	Message type: t
Advertise options:
	Scope: All
	Throttled? No
Activity
	8c2d4624-4f83-4253-831d-20605d8da566
		Since: 0 ms. ago. 
---------------

Received discovery update from 172.17.0.1: 40717
---------------
Enabled: true
Discovery state
	UUID: 5b6c2e7d-3c63-44fb-9b5c-c5b68a76fa38
Settings
	Activity: 100 ms.
	Heartbeat: 1000ms.
	Silence: 3000 ms.
Known information:
---
[928672934]
	Proc. UUID: 8c2d4624-4f83-4253-831d-20605d8da566
Publisher:
	Topic: [928672934]
	Address: tcp://127.0.0.1:12345
	Process UUID: 8c2d4624-4f83-4253-831d-20605d8da566
	Node UUID: 71af1017-4aef-462c-9db2-2373ca6e6624
	Control address: tcp://127.0.0.1:12346
	Message type: t
Advertise options:
	Scope: All
	Throttled? No
Activity
	8c2d4624-4f83-4253-831d-20605d8da566
		Since: 0 ms. ago. 
---------------

Received discovery update from 10.0.0.195: 11319
---------------
Enabled: true
Discovery state
	UUID: 5b6c2e7d-3c63-44fb-9b5c-c5b68a76fa38
Settings
	Activity: 100 ms.
	Heartbeat: 1000ms.
	Silence: 3000 ms.
Known information:
---
[/topic3]
	Proc. UUID: 8c2d4624-4f83-4253-831d-20605d8da566
Publisher:
	Topic: [/topic3]
	Address: tcp://127.0.0.1:12345
	Process UUID: 8c2d4624-4f83-4253-831d-20605d8da566
	Node UUID: 71af1017-4aef-462c-9db2-2373ca6e6624
	Control address: tcp://127.0.0.1:12346
	Message type: type
Advertise options:
	Scope: Host
	Throttled? No
[928672934]
	Proc. UUID: 8c2d4624-4f83-4253-831d-20605d8da566
Publisher:
	Topic: [928672934]
	Address: tcp://127.0.0.1:12345
	Process UUID: 8c2d4624-4f83-4253-831d-20605d8da566
	Node UUID: 71af1017-4aef-462c-9db2-2373ca6e6624
	Control address: tcp://127.0.0.1:12346
	Message type: t
Advertise options:
	Scope: All
	Throttled? No
Activity
	8c2d4624-4f83-4253-831d-20605d8da566
		Since: 0 ms. ago. 
---------------

Received discovery update from 172.17.0.1: 40762
---------------
Enabled: true
Discovery state
	UUID: 5b6c2e7d-3c63-44fb-9b5c-c5b68a76fa38
Settings
	Activity: 100 ms.
	Heartbeat: 1000ms.
	Silence: 3000 ms.
Known information:
---
[/topic3]
	Proc. UUID: 8c2d4624-4f83-4253-831d-20605d8da566
Publisher:
	Topic: [/topic3]
	Address: tcp://127.0.0.1:12345
	Process UUID: 8c2d4624-4f83-4253-831d-20605d8da566
	Node UUID: 71af1017-4aef-462c-9db2-2373ca6e6624
	Control address: tcp://127.0.0.1:12346
	Message type: type
Advertise options:
	Scope: Host
	Throttled? No
[928672934]
	Proc. UUID: 8c2d4624-4f83-4253-831d-20605d8da566
Publisher:
	Topic: [928672934]
	Address: tcp://127.0.0.1:12345
	Process UUID: 8c2d4624-4f83-4253-831d-20605d8da566
	Node UUID: 71af1017-4aef-462c-9db2-2373ca6e6624
	Control address: tcp://127.0.0.1:12346
	Message type: t
Advertise options:
	Scope: All
	Throttled? No
Activity
	8c2d4624-4f83-4253-831d-20605d8da566
		Since: 0 ms. ago. 
---------------
	* Sending BYE msg []
[       OK ] DiscoveryTest.TestAdvertise (1241 ms)
[ RUN      ] DiscoveryTest.TestAdvertiseSameProc
Discovery::Discovery(8c2d4624-4f83-4253-831d-20605d8da566, 224.0.0.7, 11319)
 No environment read: determineInterfaces
Discovery::RegisterNetIFace(10.0.0.195)
netIface == this->hostAddr 10.0.0.195 == 172.17.0.1
netIface == this->hostAddr[false]
succeed[true]
Discovery::RegisterNetIFace(172.17.0.1)
netIface == this->hostAddr 172.17.0.1 == 172.17.0.1
netIface == this->hostAddr[true]
succeed[true]
Discovery::Discovery(8c2d4624-4f83-4253-831d-20605d8da566, 224.0.0.7, 11319)
 No environment read: determineInterfaces
Discovery::RegisterNetIFace(10.0.0.195)
netIface == this->hostAddr 10.0.0.195 == 172.17.0.1
netIface == this->hostAddr[false]
succeed[true]
Discovery::RegisterNetIFace(172.17.0.1)
netIface == this->hostAddr 172.17.0.1 == 172.17.0.1
netIface == this->hostAddr[true]
succeed[true]
[       OK ] DiscoveryTest.TestAdvertiseSameProc (1297 ms)
[ RUN      ] DiscoveryTest.TestDiscover
Discovery::Discovery(8c2d4624-4f83-4253-831d-20605d8da566, 224.0.0.7, 11319)
 No environment read: determineInterfaces
Discovery::RegisterNetIFace(10.0.0.195)
netIface == this->hostAddr 10.0.0.195 == 172.17.0.1
netIface == this->hostAddr[false]
succeed[true]
Discovery::RegisterNetIFace(172.17.0.1)
netIface == this->hostAddr 172.17.0.1 == 172.17.0.1
netIface == this->hostAddr[true]
succeed[true]
Discovery::Discovery(5b6c2e7d-3c63-44fb-9b5c-c5b68a76fa38, 224.0.0.7, 11319)
 No environment read: determineInterfaces
Discovery::RegisterNetIFace(10.0.0.195)
netIface == this->hostAddr 10.0.0.195 == 172.17.0.1
netIface == this->hostAddr[false]
succeed[true]
Discovery::RegisterNetIFace(172.17.0.1)
netIface == this->hostAddr 172.17.0.1 == 172.17.0.1
netIface == this->hostAddr[true]
succeed[true]
[       OK ] DiscoveryTest.TestDiscover (225 ms)
[ RUN      ] DiscoveryTest.TestUnadvertise
Discovery::Discovery(8c2d4624-4f83-4253-831d-20605d8da566, 224.0.0.7, 11319)
 No environment read: determineInterfaces
Discovery::RegisterNetIFace(10.0.0.195)
netIface == this->hostAddr 10.0.0.195 == 172.17.0.1
netIface == this->hostAddr[false]
succeed[true]
Discovery::RegisterNetIFace(172.17.0.1)
netIface == this->hostAddr 172.17.0.1 == 172.17.0.1
netIface == this->hostAddr[true]
succeed[true]
Discovery::Discovery(5b6c2e7d-3c63-44fb-9b5c-c5b68a76fa38, 224.0.0.7, 11319)
 No environment read: determineInterfaces
Discovery::RegisterNetIFace(10.0.0.195)
netIface == this->hostAddr 10.0.0.195 == 172.17.0.1
netIface == this->hostAddr[false]
succeed[true]
Discovery::RegisterNetIFace(172.17.0.1)
netIface == this->hostAddr 172.17.0.1 == 172.17.0.1
netIface == this->hostAddr[true]
succeed[true]
[       OK ] DiscoveryTest.TestUnadvertise (1533 ms)
[ RUN      ] DiscoveryTest.TestNodeBye
Discovery::Discovery(8c2d4624-4f83-4253-831d-20605d8da566, 224.0.0.7, 11319)
 No environment read: determineInterfaces
Discovery::RegisterNetIFace(10.0.0.195)
netIface == this->hostAddr 10.0.0.195 == 172.17.0.1
netIface == this->hostAddr[false]
succeed[true]
Discovery::RegisterNetIFace(172.17.0.1)
netIface == this->hostAddr 172.17.0.1 == 172.17.0.1
netIface == this->hostAddr[true]
succeed[true]
Discovery::Discovery(5b6c2e7d-3c63-44fb-9b5c-c5b68a76fa38, 224.0.0.7, 11319)
 No environment read: determineInterfaces
Discovery::RegisterNetIFace(10.0.0.195)
netIface == this->hostAddr 10.0.0.195 == 172.17.0.1
netIface == this->hostAddr[false]
succeed[true]
Discovery::RegisterNetIFace(172.17.0.1)
netIface == this->hostAddr 172.17.0.1 == 172.17.0.1
netIface == this->hostAddr[true]
succeed[true]
[       OK ] DiscoveryTest.TestNodeBye (1366 ms)
[ RUN      ] DiscoveryTest.TestTwoPublishersSameTopic
Discovery::Discovery(8c2d4624-4f83-4253-831d-20605d8da566, 224.0.0.7, 11319)
 No environment read: determineInterfaces
Discovery::RegisterNetIFace(10.0.0.195)
netIface == this->hostAddr 10.0.0.195 == 172.17.0.1
netIface == this->hostAddr[false]
succeed[true]
Discovery::RegisterNetIFace(172.17.0.1)
netIface == this->hostAddr 172.17.0.1 == 172.17.0.1
netIface == this->hostAddr[true]
succeed[true]
Discovery::Discovery(5b6c2e7d-3c63-44fb-9b5c-c5b68a76fa38, 224.0.0.7, 11319)
 No environment read: determineInterfaces
Discovery::RegisterNetIFace(10.0.0.195)
netIface == this->hostAddr 10.0.0.195 == 172.17.0.1
netIface == this->hostAddr[false]
succeed[true]
Discovery::RegisterNetIFace(172.17.0.1)
netIface == this->hostAddr 172.17.0.1 == 172.17.0.1
netIface == this->hostAddr[true]
succeed[true]
[       OK ] DiscoveryTest.TestTwoPublishersSameTopic (525 ms)
[ RUN      ] DiscoveryTest.TestActivity
Discovery::Discovery(659552054, 224.0.0.7, 11319)
 No environment read: determineInterfaces
Discovery::RegisterNetIFace(10.0.0.195)
netIface == this->hostAddr 10.0.0.195 == 172.17.0.1
netIface == this->hostAddr[false]
succeed[true]
Discovery::RegisterNetIFace(172.17.0.1)
netIface == this->hostAddr 172.17.0.1 == 172.17.0.1
netIface == this->hostAddr[true]
succeed[true]
Discovery::Discovery(1281088782, 224.0.0.7, 11319)
 No environment read: determineInterfaces
Discovery::RegisterNetIFace(10.0.0.195)
netIface == this->hostAddr 10.0.0.195 == 172.17.0.1
netIface == this->hostAddr[false]
succeed[true]
Discovery::RegisterNetIFace(172.17.0.1)
netIface == this->hostAddr 172.17.0.1 == 172.17.0.1
netIface == this->hostAddr[true]
succeed[true]
[       OK ] DiscoveryTest.TestActivity (5253 ms)
[ RUN      ] DiscoveryTest.WrongGzIp
(DiscoveryTest) Previous GZ_IP: 
(DiscoveryTest) New GZ_IP: 127.0.0.0
(DisoveryTest) discovery1(8c2d4624-4f83-4253-831d-20605d8da566, 224.0.0.7, 11319)
Discovery::Discovery(8c2d4624-4f83-4253-831d-20605d8da566, 224.0.0.7, 11319)
 Read env GZ_IP: 127.0.0.0
Discovery::RegisterNetIFace(127.0.0.0)
netIface == this->hostAddr 127.0.0.0 == 127.0.0.0
netIface == this->hostAddr[true]
succeed[true]
/home/dharini/gazebo/garden_ws/src/ign-transport/src/Discovery_TEST.cc:552: Failure
Expected equality of these values:
  discovery1.HostAddr()
    Which is: "127.0.0.0"
  "127.0.0.1"
[  FAILED  ] DiscoveryTest.WrongGzIp (0 ms)
[ RUN      ] DiscoveryTest.WrongGzIp2
(DiscoveryTest) Previous GZ_IP: 
(DiscoveryTest) New GZ_IP: 500.0.0.0
(DisoveryTest) discovery1(8c2d4624-4f83-4253-831d-20605d8da566, 224.0.0.7, 11319)
Discovery::Discovery(8c2d4624-4f83-4253-831d-20605d8da566, 224.0.0.7, 11319)
 Read env GZ_IP: 500.0.0.0
Discovery::RegisterNetIFace(500.0.0.0)
Error setting socket option (IP_MULTICAST_IF).
netIface == this->hostAddr 500.0.0.0 == 500.0.0.0
netIface == this->hostAddr[true]
succeed[false]
Discovery::RegisterNetIFace(127.0.0.1)
Did you set the environment variable IGN_IP with a correct IP address? 
  [500.0.0.0] seems an invalid local IP address.
  Using 127.0.0.1 as hostname.
[       OK ] DiscoveryTest.WrongGzIp2 (0 ms)
[----------] 12 tests from DiscoveryTest (12845 ms total)

[----------] Global test environment tear-down
[==========] 12 tests from 1 test suite ran. (12845 ms total)
[  PASSED  ] 11 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] DiscoveryTest.WrongGzIp

 1 FAILED TEST

```
</pre>

**Comment by methylDragon** [comment]
I'm on: focal: `5.13.0-51-generic #58~20.04.1-Ubuntu SMP`

The test passes on my setup.

image

<details>

```
$ ./build/gz-transport12/bin/UNIT_Discovery_TEST --gtest_filter="*WrongGzIp*"
Running main() from /home/methyldragon/Desktop/ign_to_gz_migration/finale_ws/src/gz-transport/test/gtest_vendor/src/gtest_main.cc
Note: Google Test filter = *WrongGzIp*
[==========] Running 2 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 2 tests from DiscoveryTest
[ RUN      ] DiscoveryTest.WrongGzIp
(DiscoveryTest) Previous GZ_IP: 
(DiscoveryTest) New GZ_IP: 127.0.0.0
(DisoveryTest) discovery1(c908dd2a-7bcb-446c-a870-aaa4f207dc4f, 224.0.0.7, 11319)
Discovery::Discovery(c908dd2a-7bcb-446c-a870-aaa4f207dc4f, 224.0.0.7, 11319)
 Read env GZ_IP: 127.0.0.0
Discovery::RegisterNetIFace(127.0.0.0)
Error setting socket option (IP_MULTICAST_IF).
netIface == this->hostAddr 127.0.0.0 == 127.0.0.0
netIface == this->hostAddr[true]
succeed[false]
Discovery::RegisterNetIFace(127.0.0.1)
Did you set the environment variable IGN_IP with a correct IP address? 
  [127.0.0.0] seems an invalid local IP address.
  Using 127.0.0.1 as hostname.
[       OK ] DiscoveryTest.WrongGzIp (0 ms)
[ RUN      ] DiscoveryTest.WrongGzIp2
(DiscoveryTest) Previous GZ_IP: 
(DiscoveryTest) New GZ_IP: 500.0.0.0
(DisoveryTest) discovery1(c908dd2a-7bcb-446c-a870-aaa4f207dc4f, 224.0.0.7, 11319)
Discovery::Discovery(c908dd2a-7bcb-446c-a870-aaa4f207dc4f, 224.0.0.7, 11319)
 Read env GZ_IP: 500.0.0.0
Discovery::RegisterNetIFace(500.0.0.0)
Error setting socket option (IP_MULTICAST_IF).
netIface == this->hostAddr 500.0.0.0 == 500.0.0.0
netIface == this->hostAddr[true]
succeed[false]
Discovery::RegisterNetIFace(127.0.0.1)
Did you set the environment variable IGN_IP with a correct IP address? 
  [500.0.0.0] seems an invalid local IP address.
  Using 127.0.0.1 as hostname.
[       OK ] DiscoveryTest.WrongGzIp2 (0 ms)
[----------] 2 tests from DiscoveryTest (0 ms total)

[----------] Global test environment tear-down
[==========] 2 tests from 1 test suite ran. (0 ms total)
[  PASSED  ] 2 tests.
```

</details>

**Comment by mjcarroll** [comment]
This seems to be the difference between the test passing and failing.  On @methylDragon 's system, this call fails, where everywhere else it succeeds:

```
Discovery::RegisterNetIFace(127.0.0.0)
Error setting socket option (IP_MULTICAST_IF).
```

**Comment by caguero** [comment]
The test fails for me as well on Focal with kernel `5.15.0-41-generic #44~20.04.1-Ubuntu SMP`.

**Pull request closed without merging**
