### PR TITLE
Re-enable tests of bash completion functions for gz

### PR DESCRIPTION
**Pull request by mjcarroll**
Follow-up from #478

### CODE REVIEW

**Review by caguero — COMMENTED** [review]
Thanks!

`homebrew` looks unhappy

**Comment by mjcarroll** [comment]
> homebrew looks unhappy

I'm not sure these tests worked on homebrew before, I will limit them to just Linux.

**Comment by mjcarroll** [comment]
Trying something slightly different and starting with `/usr/bin/bash` and falling back to `/bin/bash` if that isn't available.

**Comment by mjcarroll** [comment]
@scpeters did a brief inspection for me on macOS and things didn't seem to work, likely because of some security mechanism of the operating system.  Since the value of this test is mainly in checking the flags for consistency and keeping them in sync between the completion scripts and the executables, running cross-platform isn't really necessary here.

**Review by caguero — APPROVED** [review]

**Pull request merged**
