### PR TITLE
Use new ignition-specific formatter

### PR DESCRIPTION
**Pull request by mjcarroll**
Requires ignitionrobotics/ign-utils#42

Signed-off-by: Michael Carroll <michael@openrobotics.org>

### CODE REVIEW

**Review by chapulina — COMMENTED** [review]
Can we use it on `service_main` too?

https://github.com/gazebosim/gz-transport/blob/ign-transport11/src/cmd/service_main.cc

**Comment by mjcarroll** [comment]
> Can we use it on service_main too?

Sure thing, I'm not sure why that wasn't included originally, maybe this was just a prototype.

**Review by caguero — COMMENTED** [review]
I made very minor tweaks in [fd9f63b](https://github.com/gazebosim/gz-transport/pull/296/commits/fd9f63b56e7ad99cd0fb879154a1aba07be29bf9).

**Review by caguero — APPROVED** [review]

**Comment by mjcarroll** [comment]
I actually meant to add `log` to this as well, but that can probably be done in a follow-up.

**Pull request merged**
